version : "3"
services:
    app:
        build: .
        container_name: kmong_app
        environment:
            PORT : 9000
        ports:
            - "9000:9000"
    db:
        image: redis:latest
        container_name: kmong_redis
        ports:
            - "6379:6379"
      
